name: 'Reset database'

inputs:
  id:
    description: 'Runner id'
    required: true
  password:
    description: 'Database password'
    required: true
  name:
    description: 'Base database name'
    required: true
    default: 'test'
  username:
    description: 'Database username'
    required: true
    default: 'forge'

outputs:
  name:
    description: "Database name for this runner"
    value: ${{ steps.database.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Setup database
      id: database
      shell: bash
      run: |
        DB_DATABASE="${{ inputs.name }}_${{ inputs.id }}"

        DROP_DB="DROP DATABASE IF EXISTS ${DB_DATABASE};"
        CREATE_DB="CREATE DATABASE ${DB_DATABASE};"
        mysql --user=${{ inputs.username }} --password="${{ inputs.password }}" --execute="${DROP_DB} ${CREATE_DB}"

        echo "Database: ${DB_DATABASE}"
        echo "NAME=${DB_DATABASE}" >> $GITHUB_OUTPUT
