name: 'S.A.L. status'

inputs:
  secret:
    description: 'Secret, shhh...'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SAL_SECRET: ${{ inputs.secret }}
        PR_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        if [ -z "$PR_SHA" ]; then
          GH_SHA=$GITHUB_SHA
        else
          GH_SHA=$PR_SHA
        fi

        vi-tools sal:status \
          --user=${{ github.repository_owner }} \
          --repo=${{ github.event.repository.name }} \
          --sha1=${GH_SHA}
