name: 'S.A.L. status'

inputs:
  secret:
    description: 'Secret, shhh...'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SAL_SECRET: ${{ inputs.secret }}
      run: |
        vi-tools sal:status \
          --user=${{ github.repository_owner }} \
          --repo=${{ github.event.repository.name }} \
          --sha1=${{ github.event.after }}
