name: 'Start S.A.L.'

inputs:
  secret:
    description: 'Secret, shhh...'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Start'
      shell: bash
      env:
        SAL_SECRET: ${{ inputs.secret }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        REF: ${{ github.ref }}
        HEAD_REF: ${{ github.head_ref }}
        PR_URL: ${{ github.event.pull_request._links.html.href }}
        GH_USER: ${{ github.repository_owner }}
        GH_REPO: ${{ github.event.repository.name }}
        PR_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        if [ -z "$HEAD_REF" ]; then
          BRANCH=${REF#refs/heads/}
        else
          BRANCH=$HEAD_REF
        fi

        if [ -z "$PR_SHA" ]; then
          GH_SHA=$GITHUB_SHA
        else
          GH_SHA=$PR_SHA
        fi

        echo "User:         ${GH_USER}"
        echo "Repository:   ${GH_REPO}"
        echo "SHA1:         ${GH_SHA}"
        echo "PR:           ${PR_URL}"
        echo "Branch:       ${BRANCH}"

        echo "$GITHUB_CONTEXT"

        vi-tools sal:build --user=${GH_USER} --repo=${GH_REPO} --sha1=${GH_SHA} --pr_urls=${PR_URL} --branch=${BRANCH}
